/*

Code generated by Symars.
Symars is licensed under MIT licnese.
Repository: https://github.com/Da1sypetals/Symars

*/

#[inline]
pub fn trigonometric_functions(a: f64, b: f64, c: f64) -> f64 {
    (((b).cos()) * ((c).tan())) + ((a).sin())
}
