
/*

* Code generated by Symars. Thank you for using Symars!
  Symars is licensed under MIT licnese.
  Repository: https://github.com/Da1sypetals/Symars

* Computation code is not intended for manual editing.

* If you find an error,
  or if you believe Symars generates incorrect result, 
  please raise an issue under our repo with minimal reproducible example.

*/



#[inline]
pub  fn many_many(a: f64, b: f64, c: f64, d: f64, e: f64, f: f64, g: f64, h: f64) -> f64 {

    (-(((3.14159265358979_f64) * (((((d) * ((e).recip())) + (((-(h)) + ((f) * (g))).ln())).abs()).cbrt()) * ((c).cosh()) * ((if (0.473417601666430_f64) * (a) * ((a) + (b) + (-(c))) != 0_f64 {((((0.473417601666430_f64) * (a) * ((a) + (b) + (-(c)))).sin()) / (0.473417601666430_f64) * (a) * ((a) + (b) + (-(c))))} else {1_f64}))).tanh())) + ((((((b) + (((c) + (-(a))).powf((0.333333333333333_f64) + (1.83928675521416_f64)))).sqrt()).exp()) + (((0.600000000000000_f64) + ((4.23076923076923_f64).powf(2.71828182845905_f64)) + (((c) + (-(a))).powf(0.250000000000000_f64)) + (-(0.577215664901533_f64)) + (((14.1444000000000_f64) * (a)).ln())).sin())).abs())

}
