from enum import Enum


class DType(Enum):
    F32 = 0
    F64 = 1


def funcname(name, mi, ni):
    return f"{name}_{mi}_{ni}"


HEAD = """
/*

Code generated by Symars.
Symars is licensed under MIT licnese.
Repository: https://github.com/Da1sypetals/Symars

*/
"""


def watermarked(code):
    return f"{HEAD}\n{code.replace(HEAD, '')}"


def func_template(name, param_list, return_value_type, code, inline: bool = True):
    code = f"""


{"#[inline]" if inline else ""}
pub fn {name}({param_list}) -> {return_value_type} {{

    {code}

}}
"""
    return watermarked(code)
